[project]
name = "rag-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cerebras-cloud-sdk>=1.50.1",
    "chromadb>=1.0.21",
    "docling>=2.52.0",
    "jq>=1.10.0",
    "langchain>=0.3.27",
    "langchain-cerebras>=0.5.0",
    "langchain-community>=0.3.29",
    "langchain-core>=0.3.76",
    "langchain-google-genai>=2.1.10",
    "python-dotenv>=1.1.1",
    "pymongo>=4.8.0",
]
